### ISSUE TITLE
lxqt-admin-time doesn't work on non-systemd GNU/Linux systems

### ISSUE THREAD

**Issue by Fat-Zer** [lxqt/lxqt-admin#136]
Please provide a build-time option to use a generic backend. 

It's most likely will be ok to use the same as for freebsd.

**Comment by chris2553** [comment]
I've created a patch that replicates most of the FreeBSD solution for a Linux system that doesn't have systemd. The only bit that I haven't implemented is that which enables/disables use of NTP. I don't have a system on which I could test that and quick look around the systemdless distros reveals a variety of ways to configure it on/off. Instead I hide the ntp checkbox at runtime on a Linux system that doesn't have systemd. The patch is attached. I can't send a pull request becauase I don't have the git skills required. I've zipped that patch so that I can attach it.
[lxqt-admin-0.15.0-nosystemd.patch.zip](https://github.com/lxqt/lxqt-admin/files/4746827/lxqt-admin-0.15.0-nosystemd.patch.zip)

**Comment by luis-pereira** [comment]
@chris2553 Will take a look, ASAP.

**Comment by chris2553** [comment]
Ping!

**Comment by chris2553** [comment]
Sorry, I don't see why your broken FreeBSD system affects this change. My patch is for linux systems that do not run systemd.

**Comment by luis-pereira** [comment]
I made a terrible confusion.

**Comment by luis-pereira** [comment]
@chris2553 Just applied your patch to the git tree and rebased it against the current master.
The result is [here](https://github.com/lxqt/lxqt-admin/pull/216). Review and discussion will happen there.

**Comment by jsm222** [comment]
Is this a case of a double negation bug, or is the FreeBSD implementation forgotten? The following downstream patch will be added, which fixes lxqt-admin-time on FreeBSD..
```diff
cat files/patch-lxqt-admin-time_datetime.cpp 
--- lxqt-admin-time/datetime.cpp.orig	2021-11-09 17:54:52 UTC
+++ lxqt-admin-time/datetime.cpp
@@ -70,7 +70,7 @@ void DateTimePage::reload()
     ui->edit_time->setTime(QTime::currentTime());
 
     ui->localRTC->setChecked(mLocalRtc);
-#ifndef NO_SYSTEMD
+#ifdef NO_SYSTEMD
     ui->ntp->setChecked(mUseNtp);
 #else
     ui->ntp->setChecked(false);
 ```

**Comment by chris2553** [comment]
On 09/11/2021 18:04, Jesper Schmitz Mouridsen wrote:
> Is this a case of a double negation bug, or is the FreeBSD implementation forgotten? The following downstream patch will
> be added, which fixes lxqt-admin-time on FreeBSD..
> 

No, I don't think it is a bug. NO_SYSTEMD will be defined only if systemd is not installed on the system. So, if it's
not defined, we just set the set the checkbox that shows which of ntp or systemd's date/time component is the user's
current choice. If is is defined, we disable the use of ntp and hide the check box as explained at
https://github.com/lxqt/lxqt-admin/issues/136.

However, I think my changes to lxqt-admin-time/CMakeLists.txt may have broken date and time setting on FreeBSD. I added
the check whether systemd was installed on the system and, if not, set NO_SYSTEMD. As far as I'm aware FreeBSD does not
include systemd, so NO_SYSTEMD will not be defined and the wrong code will be compiled in lxqt-admin-time/datetime.cpp.

Does the attached patch get things working again on FreeBSD?

Chris

**Comment by chris2553** [comment]
The patch I mention in my post 30 minutes ago, seems to have been dropped.  This is it:

--- lxqt-admin-1.0.0/lxqt-admin-time/CMakeLists.txt.orig        2021-11-10 19:58:57.988708301 +0000
+++ lxqt-admin-1.0.0/lxqt-admin-time/CMakeLists.txt     2021-11-10 20:01:43.784715265 +0000
@@ -59,11 +59,13 @@ lxqt_translate_desktop(DESKTOP_FILES
 lxqt_app_translation_loader(lxqt-admin-time_QM_LOADER ${PROJECT_NAME})
 #************************************************
 
+if(${CMAKE_SYSTEM_NAME} MATCHES "Linux")
 find_package(PkgConfig QUIET)
 pkg_check_modules(LIBSYSTEMD QUIET libsystemd)
 if(NOT LIBSYSTEMD_FOUND)
     add_definitions(-DNO_SYSTEMD)
 endif()
+endif()
 
 add_executable(lxqt-admin-time
     ${lxqt-admin-time_SRCS}

**Comment by chris2553** [comment]
Thinko...

On 10/11/2021 20:12, Chris Clayton wrote:
> 
> 
> On 09/11/2021 18:04, Jesper Schmitz Mouridsen wrote:
>> Is this a case of a double negation bug, or is the FreeBSD implementation forgotten? The following downstream patch will
>> be added, which fixes lxqt-admin-time on FreeBSD..
>>
> 
> No, I don't think it is a bug. NO_SYSTEMD will be defined only if systemd is not installed on the system. So, if it's
> not defined, we just set the set the checkbox that shows which of ntp or systemd's date/time component is the user's
> current choice. If is is defined, we disable the use of ntp and hide the check box as explained at
> https://github.com/lxqt/lxqt-admin/issues/136.
> 
> However, I think my changes to lxqt-admin-time/CMakeLists.txt may have broken date and time setting on FreeBSD. I added
> the check whether systemd was installed on the system and, if not, set NO_SYSTEMD. As far as I'm aware FreeBSD does not
> include systemd, so NO_SYSTEMD will not be defined and the wrong code will be compiled in lxqt-admin-time/datetime.cpp.
> 
	                         ^^^^^^^^^^^
	                         will be

**Comment by jsm222** [comment]
if(NOT LIBSYSTEMD_FOUND)
    add_definitions(-DNO_SYSTEMD)
endif()
so on freebsd we have NO_SYSTEMD defined. 

In the code the proper FreeBSD code is guarded by #ifndef NO_SYSTEMD and not #ifdef NO_SYSTEMD 

if not defined NO_SYSTEMD computes to "HAS_SYSTEMD"

**Comment by chris2553** [comment]
On 12/11/2021 13:38, Jesper Schmitz Mouridsen wrote:
> if(NOT LIBSYSTEMD_FOUND)
> add_definitions(-DNO_SYSTEMD)
> endif()
> so on freebsd we have NO_SYSTEMD defined.
> 
> In the code the proper FreeBSD code is guarded by #ifndef NO_SYSTEMD and not #ifdef NO_SYSTEMD
> 
> if not defined NO_SYSTEMD computes to "HAS_SYSTEMD"

That's correct.

Have you tried the fix for FreeBSD that I posted on Saturday?

**Comment by jsm222** [comment]
Just did.
```diff
cat patch-lxqt-admin-time_CMakeLists.txt 
--- lxqt-admin-time/CMakeLists.txt.orig 2021-11-12 15:20:13 UTC
+++ lxqt-admin-time/CMakeLists.txt
@@ -58,13 +58,13 @@ lxqt_translate_desktop(DESKTOP_FILES
 
 lxqt_app_translation_loader(lxqt-admin-time_QM_LOADER ${PROJECT_NAME})
 #************************************************
-
+if(${CMAKE_SYSTEM_NAME} MATCHES "Linux")
 find_package(PkgConfig QUIET)
 pkg_check_modules(LIBSYSTEMD QUIET libsystemd)
 if(NOT LIBSYSTEMD_FOUND)
     add_definitions(-DNO_SYSTEMD)
 endif()
-
+endif()
 add_executable(lxqt-admin-time
     ${lxqt-admin-time_SRCS}
     ${UIS}
```
works..
