### ISSUE TITLE
lxqt-admin-time doesn't list UTC

### ISSUE THREAD

**Issue by bushcountysheriff** [lxqt/lxqt-admin#254]
##### Expected Behavior

Must list UTC under timezones

##### Current Behavior

UTC is absent

##### Possible Solution

I'm assuming the program is essentially parsing `/usr/share/zoneinfo/` in some way, in which case UTC has to be listed unless it was hidden on purpose. If so, please bring it back.

##### Steps to Reproduce (for bugs)

1. Boot Arch
2. Login to lxqt session
3. open lxqt time
4. view the listed timezones

##### Context

I often change timezones (because I travel). I've been using `timedatectl` for this before I discovered that lxqt-admin-time has an option for that (PAM support included for auth). However I can't find UTC in the list.

##### System Information

* Distribution & Version:  Arch Linux
* Kernel: 5.14.11
* Qt Version: 5.15.2
* liblxqt Version: 0.17
* lxqt-build-tools Version: -
* Package version: 0.17

**Comment by stefonarch** [comment]
So this should be implemented also for GMT, EST, MET and all others.

> I often change timezones (because I travel)

FYI: worldclock can display many configured timezones on middleclick.

**Comment by bushcountysheriff** [comment]
Oh yes, GMT is missing.

I must say I actually use tint2 instead of lxqt-panel (tint2 has some scripting functionality I use), so no worldclock for me. But I don't think this isn't a lxqt-panel issue and I can still reproduce it with lxqt-panel.

**Comment by stefonarch** [comment]
No idea if tint2 exclude lxqt-panel, if not you can still use a short panel with only worldclock.

**Comment by chris2553** [comment]
> Realized UTC = GMT = Europe/London, which is listed.
I agree that UTC = GMT but Europe/London will include British Summer Time (BST). The clocks go forward 1 hour at 1am on the last Sunday in March, and back 1 hour at 2am on the last Sunday in October.
